# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmitry/Source/lang-23/cpp/srcfolder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmitry/Source/lang-23/cpp/srcfolder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitry/Source/lang-23/cpp/srcfolder/CMakeFiles /home/dmitry/Source/lang-23/cpp/srcfolder//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitry/Source/lang-23/cpp/srcfolder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named antlr4_runtime

# Build rule for target.
antlr4_runtime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr4_runtime
.PHONY : antlr4_runtime

# fast build rule for target.
antlr4_runtime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4_runtime.dir/build.make CMakeFiles/antlr4_runtime.dir/build
.PHONY : antlr4_runtime/fast

#=============================================================================
# Target rules for targets named antlr4_runtime-build_static

# Build rule for target.
antlr4_runtime-build_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr4_runtime-build_static
.PHONY : antlr4_runtime-build_static

# fast build rule for target.
antlr4_runtime-build_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4_runtime-build_static.dir/build.make CMakeFiles/antlr4_runtime-build_static.dir/build
.PHONY : antlr4_runtime-build_static/fast

#=============================================================================
# Target rules for targets named antlr4_runtime-build_shared

# Build rule for target.
antlr4_runtime-build_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr4_runtime-build_shared
.PHONY : antlr4_runtime-build_shared

# fast build rule for target.
antlr4_runtime-build_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4_runtime-build_shared.dir/build.make CMakeFiles/antlr4_runtime-build_shared.dir/build
.PHONY : antlr4_runtime-build_shared/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

antlr4cpp_generated_src/TLexer/TLexer.o: antlr4cpp_generated_src/TLexer/TLexer.cpp.o
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.o

# target to build an object file
antlr4cpp_generated_src/TLexer/TLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.o
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.cpp.o

antlr4cpp_generated_src/TLexer/TLexer.i: antlr4cpp_generated_src/TLexer/TLexer.cpp.i
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.i

# target to preprocess a source file
antlr4cpp_generated_src/TLexer/TLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.i
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.cpp.i

antlr4cpp_generated_src/TLexer/TLexer.s: antlr4cpp_generated_src/TLexer/TLexer.cpp.s
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.s

# target to generate assembly for a file
antlr4cpp_generated_src/TLexer/TLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.s
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.cpp.s

antlr4cpp_generated_src/TParser/TParser.o: antlr4cpp_generated_src/TParser/TParser.cpp.o
.PHONY : antlr4cpp_generated_src/TParser/TParser.o

# target to build an object file
antlr4cpp_generated_src/TParser/TParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/antlr4cpp_generated_src/TParser/TParser.cpp.o
.PHONY : antlr4cpp_generated_src/TParser/TParser.cpp.o

antlr4cpp_generated_src/TParser/TParser.i: antlr4cpp_generated_src/TParser/TParser.cpp.i
.PHONY : antlr4cpp_generated_src/TParser/TParser.i

# target to preprocess a source file
antlr4cpp_generated_src/TParser/TParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/antlr4cpp_generated_src/TParser/TParser.cpp.i
.PHONY : antlr4cpp_generated_src/TParser/TParser.cpp.i

antlr4cpp_generated_src/TParser/TParser.s: antlr4cpp_generated_src/TParser/TParser.cpp.s
.PHONY : antlr4cpp_generated_src/TParser/TParser.s

# target to generate assembly for a file
antlr4cpp_generated_src/TParser/TParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/antlr4cpp_generated_src/TParser/TParser.cpp.s
.PHONY : antlr4cpp_generated_src/TParser/TParser.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... antlr4_runtime"
	@echo "... antlr4_runtime-build_shared"
	@echo "... antlr4_runtime-build_static"
	@echo "... demo"
	@echo "... antlr4cpp_generated_src/TLexer/TLexer.o"
	@echo "... antlr4cpp_generated_src/TLexer/TLexer.i"
	@echo "... antlr4cpp_generated_src/TLexer/TLexer.s"
	@echo "... antlr4cpp_generated_src/TParser/TParser.o"
	@echo "... antlr4cpp_generated_src/TParser/TParser.i"
	@echo "... antlr4cpp_generated_src/TParser/TParser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

